"""update roles to faa 135

Revision ID: 09543a4b0ad7
Revises: 26d054d54662
Create Date: 2026-07-16 13:29:53.674347
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09543a4b0ad7'
down_revision: Union[str, None] = '26d054d54662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('accountable_executive', 'director_of_operations', 'director_of_safety', 'chief_pilot', 'director_of_maintenance', 'vp_finance', 'ops_manager', 'dispatcher', 'pilot', 'maintenance_technician', 'viewer', name='user_role', create_constraint=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('accountable_executive', 'director_of_operations', 'director_of_safety', 'chief_pilot', 'director_of_maintenance', 'vp_finance', 'ops_manager', 'dispatcher', 'pilot', 'maintenance_technician', 'viewer', name='user_role', create_constraint=True),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
