"""add leg_costs

Revision ID: 26d054d54662
Revises: b95ee2243427
Create Date: 2026-07-16 11:58:54.811067
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d054d54662'
down_revision: Union[str, None] = 'b95ee2243427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leg_costs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flight_leg_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('fuel', 'handling', 'landing', 'customs', 'parking', 'misc', name='leg_cost_category', create_constraint=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'credit', 'credit_card', 'wire', name='leg_payment_method', create_constraint=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.String(length=255), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flight_leg_id'], ['flight_legs.id'], name=op.f('fk_leg_costs_flight_leg_id_flight_legs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leg_costs'))
    )
    op.create_index(op.f('ix_leg_costs_flight_leg_id'), 'leg_costs', ['flight_leg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leg_costs_flight_leg_id'), table_name='leg_costs')
    op.drop_table('leg_costs')
    # ### end Alembic commands ###
