"""add flight_releases

Revision ID: 354736cf7053
Revises: 
Create Date: 2026-07-16 11:11:02.810670
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354736cf7053'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('release_number', sa.String(length=20), nullable=False, comment='Auto-generated release number (FR-YYYY-NNN), set by service layer'),
    sa.Column('status', sa.Enum('draft', 'released', 'amended', 'closed', name='release_status', create_constraint=True), nullable=False),
    sa.Column('mission_name', sa.String(length=255), nullable=True, comment='Optional mission / trip name'),
    sa.Column('aircraft_id', sa.String(length=36), nullable=True),
    sa.Column('origin_icao', sa.String(length=10), nullable=False),
    sa.Column('dest_icao', sa.String(length=10), nullable=False),
    sa.Column('alternate_icao', sa.String(length=10), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('est_enroute_minutes', sa.Integer(), nullable=True),
    sa.Column('route_waypoints', sa.JSON(), nullable=True, comment='Ordered list of route waypoints as [{lat, lon, ident, alt, ...}]'),
    sa.Column('pic_id', sa.String(length=36), nullable=True, comment='Pilot In Command user ID'),
    sa.Column('sic_id', sa.String(length=36), nullable=True, comment='Second In Command user ID'),
    sa.Column('pic_duty_start', sa.DateTime(timezone=True), nullable=True, comment='PIC duty period start (UTC)'),
    sa.Column('pic_duty_end', sa.DateTime(timezone=True), nullable=True, comment='PIC duty period end (UTC)'),
    sa.Column('sic_duty_start', sa.DateTime(timezone=True), nullable=True, comment='SIC duty period start (UTC)'),
    sa.Column('sic_duty_end', sa.DateTime(timezone=True), nullable=True, comment='SIC duty period end (UTC)'),
    sa.Column('weather_brief', sa.JSON(), nullable=True, comment='Weather brief per airport: {icao: {metar: ..., taf: ...}}'),
    sa.Column('notam_refs', sa.JSON(), nullable=True, comment='Array of NOTAM references / identifiers'),
    sa.Column('ramp_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('trip_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('contingency_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('alternate_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('reserve_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('arrival_fuel_lbs', sa.Float(), nullable=True),
    sa.Column('fuel_legal', sa.Boolean(), nullable=False, comment='True if fuel plan meets all regulatory requirements'),
    sa.Column('safe_for_flight', sa.Boolean(), nullable=False),
    sa.Column('maintenance_signed_by', sa.String(length=255), nullable=True, comment='Name/ID of maintenance personnel who signed'),
    sa.Column('maintenance_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mission_capability', sa.Enum('full', 'partial', 'not_capable', name='mission_capability', create_constraint=True), nullable=False),
    sa.Column('maintenance_restrictions', sa.JSON(), nullable=True, comment='Maintenance restrictions / MEL items as JSON'),
    sa.Column('gripes_open', sa.JSON(), nullable=True, comment='Array of open gripes [{id, description, reported_at, ...}]'),
    sa.Column('gripes_deferred', sa.JSON(), nullable=True, comment='Array of deferred gripes [{id, description, deferred_by, ...}]'),
    sa.Column('pic_acceptance', sa.Text(), nullable=True, comment='PIC acceptance statement or notes'),
    sa.Column('pic_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatcher_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True, comment='User ID of reviewer who last reviewed this release'),
    sa.Column('destination_risk', sa.Enum('low', 'moderate', 'high', 'extreme', name='destination_risk', create_constraint=True), nullable=True, comment='Destination risk level for hot-zone / threat assessment'),
    sa.Column('ground_security', sa.Enum('normal', 'elevated', 'high_threat', 'critical', name='ground_security', create_constraint=True), nullable=True, comment='Ground security assessment at destination'),
    sa.Column('overwater_legs', sa.Boolean(), nullable=False, comment='True if any leg is overwater (beyond gliding distance)'),
    sa.Column('etp_waypoint', sa.String(length=20), nullable=True, comment='Equal Time Point waypoint identifier for overwater legs'),
    sa.Column('customs_status', sa.Enum('not_required', 'pending', 'cleared', 'denied', name='customs_status', create_constraint=True), nullable=True, comment='Customs clearance status for international operations'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amended_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last amendment'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when release was closed'),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], name=op.f('fk_flight_releases_aircraft_id_aircraft'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_flight_releases_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flight_releases'))
    )
    op.create_index(op.f('ix_flight_releases_aircraft_id'), 'flight_releases', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_flight_releases_organization_id'), 'flight_releases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_flight_releases_release_number'), 'flight_releases', ['release_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_releases_release_number'), table_name='flight_releases')
    op.drop_index(op.f('ix_flight_releases_organization_id'), table_name='flight_releases')
    op.drop_index(op.f('ix_flight_releases_aircraft_id'), table_name='flight_releases')
    op.drop_table('flight_releases')
    # ### end Alembic commands ###
