"""add airport cost fields

Revision ID: b95ee2243427
Revises: 1eaaed9c128d
Create Date: 2026-07-16 11:51:49.349213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95ee2243427'
down_revision: Union[str, None] = '1eaaed9c128d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airports', sa.Column('landing_fee_usd', sa.Float(), nullable=True, comment='Typical landing fee for turboprop/light jet (USD)'))
    op.add_column('airports', sa.Column('overnight_parking_usd', sa.Float(), nullable=True, comment='Per-night parking fee (USD)'))
    op.add_column('airports', sa.Column('handling_fee_usd', sa.Float(), nullable=True, comment='Ramp handling fee (USD)'))
    op.add_column('airports', sa.Column('customs_fee_usd', sa.Float(), nullable=True, comment='Customs/CIQ processing fee (USD)'))
    op.add_column('airports', sa.Column('overflight_permit_cost_usd', sa.Float(), nullable=True, comment='Cost of overflight or landing permit (USD)'))
    op.add_column('airports', sa.Column('payment_type', sa.String(length=20), nullable=True, comment='Payment type: cash_only, credit, or mixed'))
    op.add_column('airports', sa.Column('landing_notes', sa.Text(), nullable=True, comment="Landing notes — e.g. 'Cash only before 5pm'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airports', 'landing_notes')
    op.drop_column('airports', 'payment_type')
    op.drop_column('airports', 'overflight_permit_cost_usd')
    op.drop_column('airports', 'customs_fee_usd')
    op.drop_column('airports', 'handling_fee_usd')
    op.drop_column('airports', 'overnight_parking_usd')
    op.drop_column('airports', 'landing_fee_usd')
    # ### end Alembic commands ###
