/** Aviation acronyms used throughout the app — hover any acronym to see its definition. */
const ACRONYMS: Record<string, string> = {
  ICAO: 'International Civil Aviation Organization — 4-letter airport code (e.g. MYNN)',
  PIC: 'Pilot in Command — the pilot responsible for the flight',
  SIC: 'Second in Command — second pilot, assists the PIC',
  FO: 'First Officer — co-pilot, second-in-command on multi-pilot aircraft',
  CAPT: 'Captain — senior pilot, the PIC on multi-pilot operations',
  VFR: 'Visual Flight Rules — flying by visual reference, good weather',
  MVFR: 'Marginal Visual Flight Rules — marginal weather, ceilings 1,000–3,000ft or visibility 3–5SM',
  IFR: 'Instrument Flight Rules — flying primarily by reference to instruments',
  LIFR: 'Low Instrument Flight Rules — low ceilings <500ft or visibility <1SM',
  METAR: 'Meteorological Aerodrome Report — current weather observation at an airport',
  TAF: 'Terminal Aerodrome Forecast — forecasted weather at an airport (usually 24–30hr)',
  NOTAM: 'Notice to Air Missions — time-critical aeronautical information (closures, hazards, outages)',
  'W&B': 'Weight and Balance — aircraft loading calculation for safe flight',
  FBO: 'Fixed Base Operator — service center at an airport (fuel, hangar, amenities)',
  MRO: 'Maintenance, Repair, and Overhaul — aircraft maintenance facility',
  ATPL: 'Airline Transport Pilot License — highest level of aircraft pilot license',
  CPL: 'Commercial Pilot License — license to fly for compensation or hire',
  PPL: 'Private Pilot License — license for personal, non-commercial flying',
  NM: 'Nautical Mile — unit of distance used in aviation (1 NM = 1.852 km)',
  ETA: 'Estimated Time of Arrival',
  ETD: 'Estimated Time of Departure',
  UTC: 'Coordinated Universal Time — aviation standard time (formerly GMT, Zulu)',
  'FL': 'Flight Level — altitude in hundreds of feet above standard pressure (e.g. FL100 = 10,000ft)',
  'AGL': 'Above Ground Level — altitude above the terrain directly below',
  'MSL': 'Mean Sea Level — altitude above average sea level',
  'SM': 'Statute Mile — land mile (1 SM = 1.609 km)',
  'KT': 'Knot — nautical miles per hour (1 KT = 1.15 mph)',
  'QNH': 'Barometric pressure adjusted to sea level — used for altitude setting on altimeter',
  'OFP': 'Operational Flight Plan — the complete flight planning document',
  SVFR: 'Special VFR — clearance to operate VFR in weather below VFR minima',
  HAZMAT: 'Hazardous Materials — dangerous goods requiring special handling',
  DGR: 'Dangerous Goods Regulations — IATA regulations for shipping hazardous materials',
  'Type Rating': 'A certification for a specific aircraft type (e.g. BT-67, K35X)',
  'Proficiency Check': 'Periodic check to verify a pilot remains competent in an aircraft type',
  'Line Check': 'Operational check conducted during regular line flying',
  'Recurrent Training': 'Regularly scheduled training to maintain currency and skills',
  'Differential Training': 'Training required when differences between similar aircraft types exist',
  ATC: 'Air Traffic Control — ground-based controllers who direct aircraft',
  ADSB: 'Automatic Dependent Surveillance-Broadcast — aircraft tracking technology',
  SODA: 'Statement of Demonstrated Ability — FAA waiver for a medical certificate',
  'Part 135': 'FAA regulations governing commuter and on-demand charter operations',
  OPS: 'Operations — the department managing flight operations',
  ETOPS: 'Extended-range Twin-engine Operations — certification for long overwater flights',
  'Flight Category': 'Classification of flying conditions: VFR, MVFR, IFR, or LIFR',
  'Duty Time': 'Total time a crew member is on duty, including flight, pre-flight, and post-flight',
  'Block Time': 'Time from aircraft pushback/chocks-off to chocks-on at destination',
  'Flight Time': 'Time from takeoff to landing (wheels-up to wheels-down)',
  'Crew Swap': 'Replacing a crew member mid-mission to comply with duty time limits',
  'Fuel Stop': 'Intermediate landing to refuel when non-stop range is insufficient',
  'Overnight': 'Mission requiring an overnight stay due to duty time or schedule constraints',
}

export default ACRONYMS
